import { NavModule, UserRole } from '@/types/uniafy';

export const NAV_MODULES: NavModule[] = [
  {
    id: 'master',
    label: 'Master & Admin',
    icon: 'Crown',
    roles: [UserRole.SUPER_ADMIN],
    items: [
      {
        id: 'ceo-dashboard',
        title: 'CEO Dashboard',
        description: 'Visão SaaS, MRR e saúde do negócio',
        icon: 'BarChart3',
        path: '/master/dashboard',
        roles: [UserRole.SUPER_ADMIN],
      },
      {
        id: 'white-label',
        title: 'White Label',
        description: 'Gestão de domínios e branding personalizado',
        icon: 'Palette',
        path: '/master/white-label',
        roles: [UserRole.SUPER_ADMIN],
      },
      {
        id: 'gestao-squads',
        title: 'Gestão de Squads',
        description: 'Hierarquia militar e distribuição de times',
        icon: 'Users',
        path: '/master/squads',
        roles: [UserRole.SUPER_ADMIN],
      },
      {
        id: 'banco-sql',
        title: 'Banco SQL',
        description: 'Execução direta de comandos no banco de dados',
        icon: 'Database',
        path: '/master/sql',
        roles: [UserRole.SUPER_ADMIN],
      },
    ],
  },
  {
    id: 'prospeccao',
    label: 'Máquina de Prospecção',
    icon: 'Radar',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
    items: [
      {
        id: 'g-hunter',
        title: 'Google Maps Hunter',
        description: 'Extração de leads com filtro de Pixel Meta',
        icon: 'Search',
        path: '/prospeccao/hunter',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'social-sniper',
        title: 'Social Sniper',
        description: 'Extração de e-mails de seguidores de concorrentes',
        icon: 'Target',
        path: '/prospeccao/sniper',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'cnpj-data',
        title: 'Receita Federal Data',
        description: 'Busca avançada de CNPJs e sócios',
        icon: 'FileText',
        path: '/prospeccao/cnpj',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'crm-vendas',
        title: 'CRM de Vendas',
        description: 'Pipeline e fechamento de contratos',
        icon: 'LayoutGrid',
        path: '/prospeccao/crm',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
    ],
  },
  {
    id: 'carteira',
    label: 'Gestão de Carteira',
    icon: 'Handshake',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
    items: [
      {
        id: 'onboarding',
        title: 'Onboarding Mágico',
        description: 'Fluxo linear de ativação de novos clientes',
        icon: 'Zap',
        path: '/carteira/onboarding',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'radar-whatsapp',
        title: 'Radar de WhatsApp',
        description: 'Monitoramento de SLA e tempo de resposta',
        icon: 'MessageSquare',
        path: '/carteira/whatsapp',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'previsao-churn',
        title: 'Previsão de Churn',
        description: 'Algoritmo de anti-cancelamento',
        icon: 'HeartPulse',
        path: '/carteira/churn',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
    ],
  },
  {
    id: 'trafego',
    label: 'Tráfego & Operação',
    icon: 'Settings',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
    items: [
      {
        id: 'lancador',
        title: 'Lançador One-Click',
        description: 'Criação de campanhas via Wizard e n8n',
        icon: 'Rocket',
        path: '/trafego/lancador',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'monitor-saldos',
        title: 'Monitor de Saldos',
        description: 'Alertas de budget e cartões de mídia',
        icon: 'Wallet',
        path: '/trafego/saldos',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'auditor-ia',
        title: 'Auditor Sentinela',
        description: 'Checklist diário e otimizações automáticas',
        icon: 'Activity',
        path: '/trafego/auditor',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
    ],
  },
  {
    id: 'inteligencia',
    label: 'Inteligência & Estratégia',
    icon: 'Brain',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
    items: [
      {
        id: 'ad-library-spy',
        title: 'Ad Library Spy',
        description: 'Monitoramento de anúncios de concorrentes',
        icon: 'Eye',
        path: '/inteligencia/spy',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'content-strategist',
        title: 'Content Strategist',
        description: 'IA para roteiros e pautas virais',
        icon: 'PenTool',
        path: '/inteligencia/conteudo',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'laboratorio-ia',
        title: 'Laboratório de IA',
        description: 'Chat com Expert Personas treinadas',
        icon: 'Microscope',
        path: '/inteligencia/lab',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
    ],
  },
  {
    id: 'relatorios',
    label: 'Relatórios & Data',
    icon: 'BarChart3',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
    items: [
      {
        id: 'agendador-reports',
        title: 'Agendador de Reports',
        description: 'Envio automático de PDFs via WhatsApp',
        icon: 'Calendar',
        path: '/relatorios/agendador',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'dashboard-live',
        title: 'Dashboard Live',
        description: 'Links públicos White Label para o cliente',
        icon: 'Globe',
        path: '/relatorios/live',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
    ],
  },
];
