import { NavModule, UserRole } from '@/types/uniafy';

export const NAV_MODULES: NavModule[] = [
  {
    id: 'mestre',
    label: 'MESTRE',
    icon: 'Crown',
    roles: [UserRole.SUPER_ADMIN],
    items: [
      {
        id: 'gestao-agencias',
        title: 'Gestão de Agências',
        description: 'Controle central de instâncias e clusters',
        icon: 'Building2',
        path: '/mestre/agencias',
        roles: [UserRole.SUPER_ADMIN],
      },
      {
        id: 'saude-sistema',
        title: 'Saúde do Sistema',
        description: 'Monitoramento de uptime e performance de rede',
        icon: 'Activity',
        path: '/mestre/saude',
        roles: [UserRole.SUPER_ADMIN],
      },
      {
        id: 'config-globais',
        title: 'Configurações Globais',
        description: 'Parâmetros mestre do ecossistema Uniafy',
        icon: 'Settings2',
        path: '/mestre/configuracoes',
        roles: [UserRole.SUPER_ADMIN],
      },
    ],
  },
  {
    id: 'agencia',
    label: 'AGÊNCIA',
    icon: 'Building',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
    items: [
      {
        id: 'painel-agencia',
        title: 'Painel da Agência',
        description: 'Métricas de LTV, Churn e faturamento global',
        icon: 'LayoutGrid',
        path: '/agencia/painel',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'ativacao-clientes',
        title: 'Ativação de Clientes',
        description: 'Onboarding, setup técnico e monitoramento de saldo',
        icon: 'ListChecks',
        path: '/agencia/ativacao',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'gestao-clientes',
        title: 'Gestão de Clientes',
        description: 'Monitoramento de saúde e carteira ativa',
        icon: 'Users',
        path: '/agencia/clientes',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'ritmo-orcamento',
        title: 'Ritmo de Orçamento',
        description: 'Pacing de investimento e segurança financeira',
        icon: 'Timer',
        path: '/agencia/orcamento',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'ciclos-renovacao',
        title: 'Ciclos de Renovação',
        description: 'Automação de cobrança e retenção',
        icon: 'RefreshCw',
        path: '/agencia/renovacao',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
    ],
  },
  {
    id: 'operacional',
    label: 'OPERACIONAL',
    icon: 'Settings',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
    items: [
      {
        id: 'painel-central',
        title: 'Painel Central',
        description: 'Métricas em tempo real',
        icon: 'LayoutDashboard',
        path: '/operacional/dashboard',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'sentinela-grupos',
        title: 'Sentinela de Grupos',
        description: 'IA de monitoramento e termômetro de atenção ao cliente',
        icon: 'Radio',
        path: '/operacional/sentinela',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'chat-multicanal',
        title: 'Chat Multicanal',
        description: 'Central de atendimento unificado',
        icon: 'MessageSquare',
        path: '/operacional/chat',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'relatorios-dinamicos',
        title: 'Relatórios Dinâmicos',
        description: 'Geração de PDFs e BI',
        icon: 'BarChart3',
        path: '/operacional/relatorios',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'analise-ia',
        title: 'Análise IA (Especialistas)',
        description: 'Insights preditivos via inteligência artificial',
        icon: 'Brain',
        path: '/operacional/analise-ia',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'criador-campanhas',
        title: 'Criador de Campanhas',
        description: 'Setup rápido de criativos e anúncios',
        icon: 'Megaphone',
        path: '/operacional/campanhas',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'agenda-operacional',
        title: 'Agenda Operacional',
        description: 'Cronograma de tarefas e otimizações',
        icon: 'Calendar',
        path: '/operacional/agenda',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'crm-leads',
        title: 'CRM de Leads',
        description: 'Funil de vendas industrial',
        icon: 'Target',
        path: '/operacional/crm',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'analises-dados',
        title: 'Análises de Dados',
        description: 'Visualização profunda de dados',
        icon: 'PieChart',
        path: '/operacional/analises',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'captacao-clientes',
        title: 'Captação de Clientes',
        description: 'Estratégias de prospecção ativa',
        icon: 'Radar',
        path: '/operacional/captacao',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'espionagem-mercado',
        title: 'Espionagem de Mercado',
        description: 'Benchmarking e monitoramento de concorrentes',
        icon: 'Eye',
        path: '/operacional/espionagem',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
    ],
  },
  {
    id: 'sistema',
    label: 'SISTEMA',
    icon: 'Laptop',
    roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
    items: [
      {
        id: 'meu-perfil',
        title: 'Meu Perfil',
        description: 'Dados de acesso e segurança',
        icon: 'User',
        path: '/sistema/perfil',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'conexoes-nuvem',
        title: 'Conexões em Nuvem',
        description: 'Integrações e APIs',
        icon: 'Zap',
        path: '/sistema/conexoes',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'notificacoes',
        title: 'Notificações',
        description: 'Logs e alertas de eventos',
        icon: 'Bell',
        path: '/sistema/notificacoes',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN, UserRole.END_USER],
      },
      {
        id: 'assinatura',
        title: 'Assinatura',
        description: 'Planos e faturamento do sistema',
        icon: 'CreditCard',
        path: '/sistema/assinatura',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'marca-branca',
        title: 'Marca Branca (White Label)',
        description: 'Personalização da interface administrativa',
        icon: 'Palette',
        path: '/sistema/white-label',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
      {
        id: 'identidade-visual',
        title: 'Identidade Visual',
        description: 'Customização de cores e logos da franquia',
        icon: 'Brush',
        path: '/sistema/identidade',
        roles: [UserRole.SUPER_ADMIN, UserRole.TENANT_ADMIN],
      },
    ],
  },
];
