import { NavModule, UserRole } from '@/types/uniafy';

export const NAV_MODULES: NavModule[] = [
  {
    id: 'mestre',
    label: 'Master',
    icon: 'Crown',
    roles: [UserRole.OWNER],
    items: [
      {
        id: 'gestao-agencias',
        title: 'Assinaturas & Financeiro',
        description: 'Controle de planos, faturamento e inadimplência',
        icon: 'Building2',
        path: '/mestre/agencias',
        roles: [UserRole.OWNER],
      },
      {
        id: 'config',
        title: 'Central de Alertas',
        description: 'Automação de notificações e réguas de cobrança',
        icon: 'Settings',
        path: '/mestre/config',
        roles: [UserRole.OWNER],
      },
      {
        id: 'banco-sql',
        title: 'Banco SQL',
        description: 'Execução direta de comandos no banco de dados',
        icon: 'Database',
        path: '/mestre/sql',
        roles: [UserRole.OWNER],
      },
      // --- SAAS SUITE ---
      {
        id: 'audit-logs',
        title: 'Logs de Auditoria',
        description: 'Rastreabilidade e segurança',
        icon: 'ShieldAlert',
        path: '/mestre/audit',
        roles: [UserRole.OWNER],
      },
      {
        id: 'product-analytics',
        title: 'Product Analytics',
        description: 'Telemetria de uso e engajamento',
        icon: 'Activity',
        path: '/mestre/analytics',
        roles: [UserRole.OWNER],
      },
      {
        id: 'saas-metrics',
        title: 'Métricas SaaS',
        description: 'Inteligência financeira (MRR, LTV)',
        icon: 'TrendingUp',
        path: '/mestre/metrics',
        roles: [UserRole.OWNER],
      },
      {
        id: 'white-label',
        title: 'Fábrica White Label',
        description: 'Domínios e Branding Personalizado',
        icon: 'Globe',
        path: '/mestre/whitelabel',
        roles: [UserRole.OWNER],
      },
      {
        id: 'gestao-planos',
        title: 'Gestão de Planos',
        description: 'Configuração de planos e preços',
        icon: 'CreditCard',
        path: '/mestre/planos',
        roles: [UserRole.OWNER],
      },
    ],
  },
  {
    id: 'growth',
    label: 'Growth',
    icon: 'Target',
    roles: [UserRole.OWNER, UserRole.AGENCY],
    items: [
      {
        id: 'g-hunter',
        title: 'G-Hunter Scraper',
        description: 'Captação ativa de leads via Google Maps',
        icon: 'Search',
        path: '/growth/hunter',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'cnpj-sniper',
        title: 'CNPJ Sniper',
        description: 'Extração industrial de dados da Receita Federal',
        icon: 'FileText',
        path: '/growth/cnpj',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'crm-prospect',
        title: 'Máquina de Vendas',
        description: 'CRM Kanban de prospecção estratégica',
        icon: 'Target',
        path: '/growth/crm',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      }
    ],
  },
  {
    id: 'agency',
    label: 'Agência',
    icon: 'Building2',
    roles: [UserRole.OWNER, UserRole.AGENCY],
    items: [
      {
        id: 'agency-users',
        title: 'Time & Acesso',
        description: 'Gestão de equipe e permissões',
        icon: 'Users',
        path: '/agency/users',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'agency-whitelabel',
        title: 'Personalização (White Label)',
        description: 'Domínio personalizado e branding',
        icon: 'Globe',
        path: '/agency/whitelabel',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'agency-clients',
        title: 'Clientes',
        description: 'CRM e integração de contas',
        icon: 'Briefcase',
        path: '/agency/clients',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'onboarding-magico',
        title: 'Onboarding',
        description: 'Setup automático de novos clientes',
        icon: 'Zap',
        path: '/agency/onboarding',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'gestao-squads',
        title: 'Squads',
        description: 'Distribuição de clientes e tarefas por equipe',
        icon: 'LayoutGrid',
        path: '/agency/squads',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'agency-integrations',
        title: 'Integrações',
        description: 'Conexão com plataformas (Meta, Google)',
        icon: 'Link',
        path: '/agency/integrations',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'agency-contracts',
        title: 'Contratos',
        description: 'Gestão de contratos e assinaturas',
        icon: 'FileSignature',
        path: '/agency/contracts',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'agency-finance',
        title: 'Financeiro',
        description: 'Controle de faturamento e dashboards',
        icon: 'CreditCard',
        path: '/agency/finance',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      },
      {
        id: 'churn-alert',
        title: 'Radar de Churn',
        description: 'Alertas preditivos de risco',
        icon: 'Siren',
        path: '/agency/churn-alert',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      }
    ],
  },
  {
    id: 'traffic',
    label: 'Tráfego',
    icon: 'Zap',
    roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
    items: [
      {
        id: 'funil-analytics',
        title: 'Funil Analytics',
        description: 'Meta + Google Ads em uma única tela',
        icon: 'BarChart3',
        path: '/traffic/analytics',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      },
      {
        id: 'auditor-campanhas',
        title: 'Auditor sentinela',
        description: 'Verificação automática de pixels e orçamentos',
        icon: 'Activity',
        path: '/traffic/auditor',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      },
      {
        id: 'otimizador-ia',
        title: 'Otimização One-Click',
        description: 'Ações em escala via IA e automação',
        icon: 'Brain',
        path: '/traffic/otimizador',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      }
    ],
  },
  {
    id: 'success',
    label: 'Clientes',
    icon: 'Users',
    roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
    items: [
      {
        id: 'portal-cliente',
        title: 'Portal White Label',
        description: 'Experiência exclusiva para o cliente final',
        icon: 'Globe',
        path: '/success/portal',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      },
      {
        id: 'aprovacao-criativos',
        title: 'Central de Aprovação',
        description: 'Workflow de aprovação de anúncios',
        icon: 'CheckCircle2',
        path: '/success/aprovacao',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      },
      {
        id: 'health-score',
        title: 'Health Score',
        description: 'Métrica de satisfação e risco de churn',
        icon: 'HeartPulse',
        path: '/success/health',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      }
    ],
  },
  {
    id: 'sistema',
    label: 'Sistema',
    icon: 'Settings',
    roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
    items: [
      {
        id: 'meu-perfil',
        title: 'Meu Perfil',
        description: 'Dados de acesso e segurança',
        icon: 'User',
        path: '/sistema/perfil',
        roles: [UserRole.OWNER, UserRole.AGENCY, UserRole.CLIENT],
      },
      {
        id: 'conexoes-nuvem',
        title: 'Conexões & APIs',
        description: 'Hub de integrações e webhooks (n8n)',
        icon: 'Share2',
        path: '/sistema/conexoes',
        roles: [UserRole.OWNER, UserRole.AGENCY],
      }
    ],
  },
];
